### PR TITLE
Updated readme to show usage without navigator

### PR DESCRIPTION
**Pull request by baspellis**
Explain how to compensate for the StatusBarAlert height

### CODE REVIEW

**Comment by gnestor** [comment]
Thanks @baspellis! I'm looking this over and I think that it may not be necessary. If you try the following code (this is essentially the code in the `ReactNativeStatusBarAlertApp` directory of this repo which doesn't use the `Navigator` component):

```js
<View style={{
  flex: 1
}}>
  <StatusBarAlert
    visible={true}
    message="Alert!"
    backgroundColor="#3CC29E"
    color="white"
    height={60}
  />
  <View style={{
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }}>
    <Text>Test</Text>
  </View>
</View>
```

we get:

simulator screen shot - iphone 8 - 2017-10-12 at 19 47 56

This doesn't require any special `zIndex` or `marginTop` styles.

**Comment by baspellis** [comment]
In my test I get this if I don't compensate for the marginTop: 
simulator screen shot - iphone 8 plus - 2017-10-13 at 12 50 41
The content view starts below the statusbar!

If I compensate for this by adding `marginTop: -60, paddingTop: 40` to the content view I get this:
simulator screen shot - iphone 8 plus - 2017-10-13 at 12 47 40
The alert is behind the content view!

Finally if I add `zIndex: 1` to the alert I get this:
simulator screen shot - iphone 8 plus - 2017-10-13 at 12 47 59
Which is as expected.

Here is the gist of the test I used: https://gist.github.com/baspellis/3ee92901f668fb78ccd56c166f3628cf

**Comment by gnestor** [comment]
Ok, I see what you mean now! 

This commit fixes that for me so that those extra CSS styles are not necessary: https://github.com/gnestor/react-native-statusbar-alert/pull/20/commits/9c024ea2f47a328f580bd16a4418a70bfe274e19

**Comment by baspellis** [comment]
Awesome. With version 0.4.0 all of it is indeed not required. Nice job.

**Comment by gnestor** [comment]
Thanks for catching that! 👍

**Pull request closed without merging**
